export const  LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const  SECRET_KEY_SUCCESS = 'SECRET_KEY_SUCCESS';
export const  SECRET_KEY_FAIL = 'SECRET_KEY_FAIL';
export const  LOGIN_FAIL= 'LOGIN_FAIL';
export const  ADMIN_SIGUP_SUCCESS= 'ADMIN_SIGUP_SUCCESS';
export const  ADMIN_SIGUP_ERROR= 'ADMIN_SIGUP_ERROR';
export const  EMAIL_EXIST= 'EMAIL_EXIST';
export const  SUCCESS= 'SUCCESS';
export const  GET_ERRORS = 'GET_ERRORS';
export const  USER_LOADED = 'USER_LOADED';

export const  TOKEN_VERIFICATION_FAIL = 'TOKEN_VERIFICATION_FAIL';


// agent

export const  AGENT_ADD_SUCCESS=' AGENT_ADD_SUCCESS';
export const  AGENT_FETCHING_SUCCESS=' FETCHING_SUCCESS';
export const AGENT_DELETE_SUCCESS = 'AGENT_DELETE_SUCCESS';
export const AGENT_UPDATE_SUCCESS = 'AGENT_UPDATE_SUCCESS'

// vendor

export const  VENDOR_ADD_SUCCESS=' VENDOR_ADD_SUCCESS';
export const  VENDOR_FETCHING_SUCCESS=' VENDOR_FETCHING_SUCCESS';
export const VENDOR_DELETE_SUCCESS = 'VENDOR_DELETE_SUCCESS';
export const VENDOR_UPDATE_SUCCESS = 'VENDOR_UPDATE_SUCCESS'

export const EMAIL_SEND_SUCCESS = 'EMAIL_SEND_SUCCESS'
export const EMAIL_SEND_FAILURE = 'EMAIL_SEND_FAILURE'


// lead
export const  GET_LEADS = 'GET_LEADS';
export const  UPDATE_LEAD = 'UPDATE_LEAD';
export const  ADD_LEAD = 'ADD_LEAD';
export const  DELETE_LEAD = 'DELETE_LEAD';




export const  DASHBORD_DATA = 'DASHBORD_DATA';

export const  CLEAR_NOTIFICATION=' CLEAR_NOTIFICATION';
export const  DISPLAY_NOTIFICATION=' DISPLAY_NOTIFICATION';


export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SEND_MESSAGE_TO_AGENT='SEND_MESSAGE_TO_AGENT'

export const STATUS_UPDATE_SUCCESS='STATUS_UPDATE_SUCCESS'
export const NOTIFICATION='NOTIFICATION'

export const DELETE_NOTIFICATION='DELETE_NOTIFICATION'


export const AGENT_ACTIVITY_SUCCESS='DELETE_NOTIFICATION'
export const AGENT_ACTIVITY_FAILURE='DELETE_NOTIFICATION'

export const AGREEMENT_DATA_FETCH='AGREEMENT_DATA_FETCH'







